### ISSUE TITLE
GPT-2 sampling fails on CPU

### ISSUE THREAD

**Issue by lostmsu** [losttech/Gradient-Samples#1]
> InvalidArgumentError : indices[0,0] = 1024 is not in [0, 1024)

Looks like an off-by-one error.

Here are the exception details:

> Python.Runtime.PythonException
>   HResult=0x80131500
>   Message=InvalidArgumentError : indices[0,0] = 1024 is not in [0, 1024)
> 	 [[Node: sample_sequence/while/model/GatherV2_1 = GatherV2[Taxis=DT_INT32, Tindices=DT_INT32, Tparams=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](sample_sequence/while/model/GatherV2_1/Enter, sample_sequence/while/model/ExpandDims, sample_sequence/while/model/h11/attn/range_1/start, ^sample_sequence/while/strided_slice/stack_2)]]
> 
> Caused by op 'sample_sequence/while/model/GatherV2_1', defined at:
>   File "C:\Users\<SCRAMBLED>\AppData\Local\conda\conda\envs\tf\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 3232, in while_loop
>     return_same_structure)
>   File "C:\Users\<SCRAMBLED>\AppData\Local\conda\conda\envs\tf\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2952, in BuildLoop
>     pred, body, original_loop_vars, loop_vars, shape_invariants)
>   File "C:\Users\<SCRAMBLED>\AppData\Local\conda\conda\envs\tf\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 2887, in _BuildLoop
>     body_result = body(*packed_vars_for_body)
>   File "C:\Users\<SCRAMBLED>\AppData\Local\conda\conda\envs\tf\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 3201, in <lambda>
>     body = lambda i, lv: (i + 1, orig_body(*lv))
>   File "C:\Users\<SCRAMBLED>\AppData\Local\conda\conda\envs\tf\lib\site-packages\tensorflow\python\ops\array_ops.py", line 2659, in gather
>     return gen_array_ops.gather_v2(params, indices, axis, name=name)
>   File "C:\Users\<SCRAMBLED>\AppData\Local\conda\conda\envs\tf\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 3761, in gather_v2
>     "GatherV2", params=params, indices=indices, axis=axis, name=name)
>   File "C:\Users\<SCRAMBLED>\AppData\Local\conda\conda\envs\tf\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
>     op_def=op_def)
>   File "C:\Users\<SCRAMBLED>\AppData\Local\conda\conda\envs\tf\lib\site-packages\tensorflow\python\util\deprecation.py", line 454, in new_func
>     return func(*args, **kwargs)
>   File "C:\Users\<SCRAMBLED>\AppData\Local\conda\conda\envs\tf\lib\site-packages\tensorflow\python\framework\ops.py", line 3155, in create_op
>     op_def=op_def)
>   File "C:\Users\<SCRAMBLED>\AppData\Local\conda\conda\envs\tf\lib\site-packages\tensorflow\python\framework\ops.py", line 1717, in __init__
>     self._traceback = tf_stack.extract_stack()
> 
> InvalidArgumentError (see above for traceback): indices[0,0] = 1024 is not in [0, 1024)
> 	 [[Node: sample_sequence/while/model/GatherV2_1 = GatherV2[Taxis=DT_INT32, Tindices=DT_INT32, Tparams=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](sample_sequence/while/model/GatherV2_1/Enter, sample_sequence/while/model/ExpandDims, sample_sequence/while/model/h11/attn/range_1/start, ^sample_sequence/while/strided_slice/stack_2)]]
> 
>   Source=Python.Runtime
>   StackTrace:
> ['  File "C:\\Users\\<SCRAMBLED>\\AppData\\Local\\conda\\conda\\envs\\tf\\lib\\site-packages\\tensorflow\\python\\client\\session.py", line 877, in run\n    run_metadata_ptr)\n', '  File "C:\\Users\\<SCRAMBLED>\\AppData\\Local\\conda\\conda\\envs\\tf\\lib\\site-packages\\tensorflow\\python\\client\\session.py", line 1100, in _run\n    feed_dict_tensor, options, run_metadata)\n', '  File "C:\\Users\\<SCRAMBLED>\\AppData\\Local\\conda\\conda\\envs\\tf\\lib\\site-packages\\tensorflow\\python\\client\\session.py", line 1272, in _do_run\n    run_metadata)\n', '  File "C:\\Users\\<SCRAMBLED>\\AppData\\Local\\conda\\conda\\envs\\tf\\lib\\site-packages\\tensorflow\\python\\client\\session.py", line 1291, in _do_call\n    raise type(e)(node_def, op, message)\n']

**Comment by lostmsu** [comment]
Happens on both Windows and Linux.

**Comment by lostmsu** [comment]
Does not repro

**Comment by ghost** [comment]
I have the same issue on my machine

**Comment by lostmsu** [comment]
@SnowSnakz which TensorFlow version are you using? The latest published version (aka Preview 7+) requires 1.15.0 exactly (1.15.1+ are missing some files).

Were you trying to train or to generate?

What OS? Is it .NET Core or .NET Framework?

**Comment by lostmsu** [comment]
Random guess: is this related to the length of the prompt? It probably has a limit.

**Comment by ghost** [comment]
@lostmsu I am using Python 3.6 with `tensorflow==1.15` installed

I didn't touch anything other than the required parameters to even run this program:
```
dotnet GPT-2.dll run -m 117M -c 1 -r ''
```
(Also as a quick suggestion, instead of allowing the Path.Combine exception to occur when the user doesn't specify `-m` and `-r`, catch the exception and let the user know what they need to define instead of forcing them to look at the code in order to figure out what needs to be set and how. 
Some people just want a working example and don't want to deal with figuring out errors like this right from the start.)

This was my prompt and my output:
```
Model prompt >>> It is finally time for your first pet!

Unhandled Exception: Python.Runtime.PythonException: InvalidArgumentError : indices[0,0] = 1024 is not in [0, 1024)
         [[node sample_sequence/while/model/GatherV2_1 (defined at \framework\ops.py:1748) ]]

Original stack trace for 'sample_sequence/while/model/GatherV2_1':
  File "\ops\control_flow_ops.py", line 2753, in while_loop
    return_same_structure)
  File "\ops\control_flow_ops.py", line 2245, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "\ops\control_flow_ops.py", line 2170, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "\ops\control_flow_ops.py", line 2705, in <lambda>
    body = lambda i, lv: (i + 1, orig_body(*lv))
  File "\util\dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "\ops\array_ops.py", line 3956, in gather
    params, indices, axis, name=name)
  File "\ops\gen_array_ops.py", line 4081, in gather_v2
    batch_dims=batch_dims, name=name)
  File "\framework\op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "\framework\ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "\framework\ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "\framework\ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

   at Python.Runtime.Exceptions.ErrorCheck(IntPtr pointer)
   at Python.Runtime.PyObject.Invoke(PyObject[] args)
   at Python.Runtime.PyObject.InvokeMethod(String name, PyObject[] args)
   at tensorflow.python.client.session.BaseSession.run(Object fetches, IDictionary`2 feed_dict, String options, String run_metadata)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at Gradient.Samples.GPT2.Gpt2Interactive.<>c__DisplayClass0_0.<Run>b__0(Session sess) in C:\Users\SnowSnakz\Downloads\Gradient-Samples-master\Gradient-Samples-master\GPT-2\Gpt2Interactive.cs:line 79
   at Gradient.ContextManagerExtensions.Use[CM,T](CM contextManager, Action`2 action)
   at Gradient.Samples.GPT2.Gpt2Interactive.Run(String modelName, String checkpoint, Nullable`1 seed, Int32 sampleCount, Int32 batchSize, Nullable`1 length, Single temperature, Int32 topK) in C:\Users\SnowSnakz\Downloads\Gradient-Samples-master\Gradient-Samples-master\GPT-2\Gpt2Interactive.cs:line 51
   at Gradient.Samples.GPT2.Gpt2Interactive.Run(String[] remainingArguments) in C:\Users\SnowSnakz\Downloads\Gradient-Samples-master\Gradient-Samples-master\GPT-2\Gpt2Interactive.cs:line 135
   at ManyConsole.CommandLineUtils.ConsoleCommand.<>c__DisplayClass13_0.<Register>b__1()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at ManyConsole.CommandLineUtils.ConsoleCommandDispatcher.DispatchCommand(IEnumerable`1 commands, String[] arguments, TextWriter consoleOut)
   at Gradient.Samples.GPT2.Gpt2Program.Main(String[] args) in C:\Users\SnowSnakz\Downloads\Gradient-Samples-master\Gradient-Samples-master\GPT-2\GPT2Program.cs:line 14```

**Comment by lostmsu** [comment]
@SnowSnakz heads up, I am able to reproduce this. Going to be a tricky one, as I just confirmed, that on GPU the issue does not happen, meaning there is a TensorFlow internal problem, that creates some discrepancy. Should still be able to figure it out.

**Comment by lostmsu** [comment]
Upstream issues: https://github.com/openai/gpt-2/issues/106 , https://github.com/nshepperd/gpt-2/issues/14

**Comment by lostmsu** [comment]
Workaround: set lower length for generated text. `-l 900` seems to be working.

**Comment by lostmsu** [comment]
Pushed a fix, that automatically limits number of generated tokens, unless run on GPU.
